title: EDU Portfolio

# Google Analytics tracking code
# google_analytics:

plugins:
    - jekyll-seo-tag

theme: "edu-portfolio"

collections:
    first:
        output: true
        permalink: /:collection/:name
        nav_include: true
        sort_by: nav_order
    second:
        output: true
        permalink: /:collection/:name
        nav_include: true
        sort_by: nav_order
    third:
        output: true
        permalink: /:collection/:name
        nav_include: true
        sort_by: nav_order

defaults:
    -
        scope:
            path: ""
            type: "first"
        values:
            layout: "course"
            nav_order: 999
    -
        scope:
            path: ""
            type: "second"
        values:
            layout: "course"
            nav_order: 999
    -
        scope:
            path: ""
            type: "third"
        values:
            layout: "course"
            nav_order: 999